# Use an official Node.js runtime as a parent image
FROM node:18

# Set the working directory in the container
WORKDIR /usr/src/app

# Install backend dependencies
COPY package*.json ./
RUN npm install --production

# Bundle app source
COPY . .

# Build backend TypeScript code
RUN npm run build

# Change into the client directory
WORKDIR /usr/src/app/client

# Install frontend dependencies
RUN npm install --production

# Build frontend Vue.js code
RUN npm run build

# Expose the port the app runs on
EXPOSE 3002

# Run the application
CMD ["npm", "start"]
